[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
num_cpus = "1.16.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
